# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

before_script:
  - rustup toolchain install beta
  - rustup component add rustfmt
  - rustup component add rustfmt --toolchain beta
  - rustup component add clippy
  - rustup component add clippy --toolchain beta

# Use cargo to test the project
test:stable:
  script:
    - rustup --version && rustc --version && cargo --version
    - cargo fmt --all -- --check
    - cargo clippy
    - cargo test --all --verbose

test:beta:
  script:
    - rustup default beta
    - rustup --version && rustc --version && cargo --version
    - cargo fmt --all -- --check
    - cargo clippy
    - cargo test --all --verbose
