# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

before_script:
  - rustup component add rustfmt
#  - rustup component add clippy

# Use cargo to test the project
test:cargo:
  script:
    - rustup --version && rustc --version && cargo --version  # Print version info for debugging
    - cargo fmt --all -- --check
    - cargo test --all --verbose
