# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

before_script:
  - rustup component add rustfmt clippy
  - rustup toolchain install beta
  - rustup component add rustfmt clippy --toolchain beta

.run_test: &run_test
  script:
    - rustup --version && rustc --version && cargo --version
    - cargo fmt --all -- --check
    - cargo clippy
    - cargo build
    - cargo test --all --verbose

# Use cargo to test the project
test:stable:
  <<: *run_test

test:beta:
  <<: *run_test
  before_script:
    - rustup default beta
